//! Discovery file publication and removal.
//!
//! Publication must be atomic, so a client never observes a half-written file.
//! The instance identifier is generated by the caller *before* publication and
//! included in the write, which means a partially written document cannot appear
//! at the published path. Removal is ownership-checked: shutdown deletes the file
//! only if the `instance_id` still belongs to the caller.

use std::path::Path;

use jarvis_protocol::{DiscoveryFile, DiscoveryReject};

/// An error raised while publishing or removing a discovery file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DiscoveryError {
    /// The record could not be written.
    Publish,
    /// The file could not be read back for validation.
    Read,
    /// The published file failed validation.
    Invalid(DiscoveryReject),
}

impl DiscoveryError {
    /// Returns the stable, namespaced error code.
    #[must_use]
    pub const fn code(&self) -> &'static str {
        match self {
            Self::Publish => "jarvis.discovery_publish",
            Self::Read => "jarvis.discovery_read",
            Self::Invalid(_) => "jarvis.discovery_invalid",
        }
    }
}

impl std::fmt::Display for DiscoveryError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Publish => formatter.write_str("the discovery file could not be published"),
            Self::Read => formatter.write_str("the discovery file could not be read back"),
            Self::Invalid(reason) => write!(formatter, "the discovery record is invalid: {reason}"),
        }
    }
}

impl std::error::Error for DiscoveryError {}

/// Publishes `record` at `path` atomically, then reads it back.
///
/// The read-back is the point: a client depends on this file, so "the write
/// returned Ok" is not proof that a valid document is what a reader will parse.
///
/// # Errors
///
/// Returns [`DiscoveryError::Publish`] when the write or replace fails,
/// [`DiscoveryError::Invalid`] when the record itself is not valid, and
/// [`DiscoveryError::Read`] when the read-back fails.
pub fn publish(path: &Path, record: &DiscoveryFile) -> Result<(), DiscoveryError> {
    record.validate().map_err(DiscoveryError::Invalid)?;
    let bytes = record.to_bytes().map_err(|_| DiscoveryError::Publish)?;

    // Reuse the proved atomic writer: owner-only temp file, write, sync, rename,
    // directory flush. The temp file is created with `create_new`, so a symlink
    // planted at the temp name cannot redirect the write.
    crate::config::atomic::write_atomic(path, &bytes).map_err(|_| DiscoveryError::Publish)?;

    let written = std::fs::read(path).map_err(|_| DiscoveryError::Read)?;
    let parsed = DiscoveryFile::parse(&written).map_err(DiscoveryError::Invalid)?;
    if parsed != *record {
        return Err(DiscoveryError::Publish);
    }
    Ok(())
}

/// Removes the discovery file only if it still belongs to `instance_id`.
///
/// # Errors
///
/// Returns [`DiscoveryError::Read`] when an existing file cannot be read. A
/// missing file is success, because the desired state is already reached.
pub fn remove_if_owned(path: &Path, instance_id: &str) -> Result<(), DiscoveryError> {
    if !path.exists() {
        return Ok(());
    }
    let bytes = std::fs::read(path).map_err(|_| DiscoveryError::Read)?;

    // An unparseable file is not provably ours, so it is left for the operator
    // rather than deleted.
    let owned = DiscoveryFile::parse(&bytes).is_ok_and(|file| file.instance_id == instance_id);
    if owned {
        std::fs::remove_file(path).map_err(|_| DiscoveryError::Publish)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use jarvis_protocol::{DISCOVERY_SCHEMA_VERSION, DiscoveryFile};

    use super::{DiscoveryError, publish, remove_if_owned};

    fn temp_dir(tag: &str) -> std::path::PathBuf {
        let dir =
            std::env::temp_dir().join(format!("jarvis-fnd007-disc-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");
        dir
    }

    fn record(instance_id: &str) -> DiscoveryFile {
        DiscoveryFile {
            schema_version: DISCOVERY_SCHEMA_VERSION,
            instance_id: instance_id.to_owned(),
            pid: std::process::id(),
            base_url: "http://127.0.0.1:43127".to_owned(),
            api_major: 1,
            started_at: "2026-09-21T00:00:00Z".to_owned(),
        }
    }

    #[test]
    fn a_published_record_is_readable_and_valid() {
        let dir = temp_dir("publish");
        let path = dir.join("discovery.json");
        publish(&path, &record("instance-a")).expect("publish succeeds");

        let bytes = std::fs::read(&path).expect("file exists");
        let parsed = DiscoveryFile::parse(&bytes).expect("valid record");
        assert_eq!(parsed.instance_id, "instance-a");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn publishing_replaces_a_previous_record_without_leaving_a_temp_file() {
        let dir = temp_dir("replace");
        let path = dir.join("discovery.json");
        publish(&path, &record("instance-a")).expect("first publish");
        publish(&path, &record("instance-b")).expect("second publish");

        let entries: Vec<String> = std::fs::read_dir(&dir)
            .expect("dir readable")
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .collect();
        assert_eq!(
            entries,
            vec!["discovery.json".to_owned()],
            "no temp file remains"
        );

        let parsed =
            DiscoveryFile::parse(&std::fs::read(&path).expect("readable")).expect("valid record");
        assert_eq!(parsed.instance_id, "instance-b");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_invalid_record_is_refused_before_it_is_written() {
        let dir = temp_dir("invalid");
        let path = dir.join("discovery.json");
        let mut unsafe_record = record("instance-a");
        unsafe_record.base_url = "http://evil.example:1".to_owned();

        let error = publish(&path, &unsafe_record).expect_err("must be refused");
        assert_eq!(error.code(), "jarvis.discovery_invalid");
        assert!(
            !path.exists(),
            "nothing may be written for an invalid record"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn removal_is_ownership_checked() {
        let dir = temp_dir("remove");
        let path = dir.join("discovery.json");

        publish(&path, &record("instance-a")).expect("publish");
        // A different instance must not delete another daemon's file.
        remove_if_owned(&path, "instance-other").expect("no error for a foreign file");
        assert!(path.exists(), "a foreign record must be left in place");

        remove_if_owned(&path, "instance-a").expect("owner removal succeeds");
        assert!(!path.exists(), "the owner may remove its own record");

        // Removing an absent file reports success: the goal state is reached.
        remove_if_owned(&path, "instance-a").expect("missing file is success");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn removal_leaves_an_unparseable_file_for_the_operator() {
        let dir = temp_dir("corrupt");
        let path = dir.join("discovery.json");
        std::fs::write(&path, b"{not json").expect("write fixture");

        remove_if_owned(&path, "instance-a").expect("no error");
        assert!(
            path.exists(),
            "an unparseable file is not provably ours and must not be deleted",
        );

        let _ = std::fs::remove_dir_all(&dir);
        let _ = DiscoveryError::Read.code();
    }
}
