//! Prints a fresh non-production release test keypair as unpadded `base64url`.
//!
//! This is a one-shot development helper. It is kept so the committed test key is
//! reproducible and auditable rather than hand-written: a hand-typed key is not a
//! key, and "why does this constant look like that" has no answer.
//!
//! ```text
//! cargo run -p jarvis-infrastructure --example gen_test_key --features dev-tools
//! ```
//!
//! The key it prints has **no trust**. It signs only visibly-marked test
//! artifacts. Production signing identities are `OWN-003` and their private keys
//! must never be generated by, or committed to, this repository.

use ed25519_dalek::{SigningKey, VerifyingKey};

fn main() {
    let mut seed = [0_u8; 32];
    if getrandom::fill(&mut seed).is_err() {
        // Abort rather than produce a key from a partial or weak fill: a
        // predictable signing key is worse than no key at all.
        eprintln!("error: the operating system did not provide entropy");
        std::process::exit(1);
    }
    let signing_key = SigningKey::from_bytes(&seed);
    let verifying_key: VerifyingKey = signing_key.verifying_key();

    println!("secret: {}", base64url(&signing_key.to_bytes()));
    println!("public: {}", base64url(&verifying_key.to_bytes()));
}

/// Encodes bytes as unpadded `base64url`.
fn base64url(input: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let mut out = String::with_capacity(input.len().div_ceil(3) * 4);
    for chunk in input.chunks(3) {
        let b0 = u32::from(chunk[0]);
        let b1 = chunk.get(1).map_or(0, |byte| u32::from(*byte));
        let b2 = chunk.get(2).map_or(0, |byte| u32::from(*byte));
        let triple = (b0 << 16) | (b1 << 8) | b2;
        out.push(char::from(ALPHABET[((triple >> 18) & 0x3f) as usize]));
        out.push(char::from(ALPHABET[((triple >> 12) & 0x3f) as usize]));
        if chunk.len() > 1 {
            out.push(char::from(ALPHABET[((triple >> 6) & 0x3f) as usize]));
        }
        if chunk.len() > 2 {
            out.push(char::from(ALPHABET[(triple & 0x3f) as usize]));
        }
    }
    out
}
